name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Aici injectăm token-ul ca variabilă de mediu
        run: docker buildx build --file Dockerfile --tag zenidro-image:$(date +%s) .
